### ISSUE TITLE
Nodding: wrong sign of offsets

### ISSUE THREAD

**Issue by pcastang** [discos/basie#34]
Offsets in nodding scans should be positive when using feeds 0 and 3, and negative when using feeds 0 and 6. In the current version is the opposite.

**Comment by jjpopski** [comment]
To point with a lateral beam, you must give an offset which has opposite sign of the feed displacement. For example, if the feed has -0.0382d displacement w.r.t the central beam, the offset given to the antenna should be   +0.0382d, because the pointing always refers to the central beam which has, in this example,  +0.0382d offset displacement w.r.t the lateral beam

**Comment by jjpopski** [comment]
Closed. Merged in master branch
